import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/home.module.css'

//components
import Navbar from '@/components/navbar'
import SectionApresentation from '@/components/homeComponents/sectionApresentation'
import SectionProjects from '@/components/homeComponents/sectionProjects'
import SectionMethods from '@/components/homeComponents/sectionMethods'
import SectionAbout from '@/components/homeComponents/sectionAbout'
import Footer from '@/components/footer'

//home page
export default function Home() {
  return (
    <>
      <Head>
        <title>Tropical Tech</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Navbar />


      <main className={styles.main}>

        <SectionApresentation />
        <SectionProjects />
        <SectionMethods />
        <SectionAbout />

        <Footer />
      </main>

    </>
  )
}
